# Generated by Django 5.1.6 on 2025-03-21 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='user',
            new_name='name',
        ),
    ]
