# Generated by Django 5.1.6 on 2025-02-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_game_tags'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-created_at'], 'verbose_name': 'Game', 'verbose_name_plural': 'Games'},
        ),
        migrations.AddField(
            model_name='game',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['-created_at'], name='product_gam_created_23ecad_idx'),
        ),
    ]
