# Generated by Django 5.1.6 on 2025-03-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_user_ticket_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default='', max_length=11, unique=True),
        ),
    ]
