# Generated by Django 5.1.6 on 2025-02-09 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_game_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_id',
        ),
    ]
