# Generated by Django 5.1.6 on 2025-03-22 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_order_orderitem_order_product_ord_created_a79a09_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='product.game'),
        ),
    ]
