# Generated by Django 5.1.6 on 2025-02-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_game_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_summary',
            field=models.TextField(blank=True, help_text='write a summary of the game story', null=True),
        ),
    ]
