# Generated by Django 5.1.6 on 2025-02-09 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_game_game_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='game_summary',
            new_name='summary',
        ),
    ]
