# Generated by Django 5.1.6 on 2025-02-10 18:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_rename_game_summary_game_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='off',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
