# Generated by Django 4.2.16 on 2025-04-04 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_customuser_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
