# Generated by Django 4.2.16 on 2025-04-04 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_delete_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='description',
        ),
    ]
