# Generated by Django 5.1.6 on 2025-02-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='site',
            field=models.CharField(default='IGN', max_length=50),
        ),
    ]
