# Generated by Django 5.1.6 on 2025-02-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_category_remove_game_genres_game_category'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='game',
            name='product_gam_created_23ecad_idx',
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['-created_at', '-off'], name='product_gam_created_bf378f_idx'),
        ),
    ]
