# Generated by Django 5.1.6 on 2025-02-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_remove_game_product_gam_created_23ecad_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='sold_count',
            field=models.IntegerField(default=0),
        ),
    ]
