# Generated by Django 5.1.6 on 2025-03-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_game_sold_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(choices=[('Login & Logout Error', 'Login & Logout Error'), ('Buying Error', 'Buying Error'), ('Other', 'Other')], max_length=50)),
                ('message', models.TextField()),
            ],
        ),
    ]
